### ISSUE TITLE
ImportError: Module use of python39.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by Rigborn4** [ranjian0/assimp-py#3]
I couldn't make it work with any python version other than 3.9 on Windows. When installing from source, it creates python39.dll file regardless of the python version.

**Comment by ranjian0** [comment]
I am not familiar with the particulars of building from source on windows but it works in the automated pypi builds so I suspect the issue may be with your system setup. 

That said, building this package should not result in creation of python39.dll. This is something that should already exist with a windows python installation.

Is there a reason you are not installing from pypi?

**Comment by Rigborn4** [comment]
I just checked. Installing from pypi works for versions 3.9 and below. (Probably because 3.10 is not added inside workflow files) Would you consider adding support for 3.10 as well ?

**Comment by ranjian0** [comment]
> I just checked. Installing from pypi works for versions 3.9 and below. (Probably because 3.10 is not added inside workflow files) Would you consider adding support for 3.10 as well ?

ok, will work on this.
