### ISSUE TITLE
wheel for python 3.11

### ISSUE THREAD

**Issue by vanous** [ranjian0/assimp-py#4]
Thank you so much for making this python bindings for assimp, much appreciated!

Could you please make a wheel for the new Python 3.11?
Thank you very much!

**Comment by ranjian0** [comment]
Many months later ... 
Resolved in v1.0.7: https://pypi.org/project/assimp-py/

**Comment by vanous** [comment]
Many thanks! I can confirm that it works well on Linux with python 3.11.0 .
